create extension if not exists pgcrypto;

create table if not exists public.products (
	id bigint generated by default as identity primary key,
	barcode text not null unique,
	name text not null,
	brand text,
	is_israeli boolean not null,
	status text not null default 'verified' check (status in ('verified', 'pending')),
	confidence numeric(4, 3) not null default 1,
	reasoning text,
	context_text text,
	verified_at timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.pending_votes (
	id bigint generated by default as identity primary key,
	barcode text not null,
	name text,
	brand text,
	is_israeli boolean not null,
	vote_count integer not null default 0,
	verify_votes integer not null default 0,
	correct_votes integer not null default 0,
	ai_confidence numeric(4, 3),
	reasoning text,
	context_text text,
	verified boolean not null default false,
	verified_at timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	unique (barcode, is_israeli)
);

alter table public.products enable row level security;
alter table public.pending_votes enable row level security;

do $$
begin
	create policy "service role manages verified products"
		on public.products
		for all
		using (auth.role() = 'service_role')
		with check (auth.role() = 'service_role');
exception
	when duplicate_object then null;
end $$;

do $$
begin
	create policy "service role manages pending votes"
		on public.pending_votes
		for all
		using (auth.role() = 'service_role')
		with check (auth.role() = 'service_role');
exception
	when duplicate_object then null;
end $$;

create or replace function public.increment_and_verify(
	p_barcode text,
	p_is_israeli boolean,
	p_vote_action text default 'verify',
	p_name text default null,
	p_brand text default null,
	p_context_text text default null,
	p_reasoning text default null,
	p_ai_confidence numeric default null
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
	v_row public.pending_votes%rowtype;
	v_vote_delta integer := 1;
	v_verify_delta integer := case when p_vote_action = 'verify' then 1 else 0 end;
	v_correct_delta integer := case when p_vote_action = 'correct' then 1 else 0 end;
	v_verified boolean := false;
	v_name text;
	v_brand text;
	v_context_text text;
	v_reasoning text;
	v_confidence numeric;
begin
	insert into public.pending_votes (
		barcode,
		name,
		brand,
		is_israeli,
		vote_count,
		verify_votes,
		correct_votes,
		ai_confidence,
		reasoning,
		context_text,
		verified,
		updated_at
	)
	values (
		p_barcode,
		p_name,
		p_brand,
		p_is_israeli,
		v_vote_delta,
		v_verify_delta,
		v_correct_delta,
		p_ai_confidence,
		p_reasoning,
		p_context_text,
		false,
		now()
	)
	on conflict (barcode, is_israeli)
	do update set
		vote_count = public.pending_votes.vote_count + excluded.vote_count,
		verify_votes = public.pending_votes.verify_votes + excluded.verify_votes,
		correct_votes = public.pending_votes.correct_votes + excluded.correct_votes,
		name = coalesce(excluded.name, public.pending_votes.name),
		brand = coalesce(excluded.brand, public.pending_votes.brand),
		ai_confidence = coalesce(excluded.ai_confidence, public.pending_votes.ai_confidence),
		reasoning = coalesce(excluded.reasoning, public.pending_votes.reasoning),
		context_text = coalesce(excluded.context_text, public.pending_votes.context_text),
		updated_at = now()
	returning * into v_row;

	v_verified := v_row.vote_count >= 3;

	if v_verified then
		update public.pending_votes
		set verified = true,
			verified_at = coalesce(verified_at, now()),
			updated_at = now()
		where id = v_row.id;

		v_name := coalesce(v_row.name, p_name, 'UNKNOWN PRODUCT');
		v_brand := coalesce(v_row.brand, p_brand, 'UNKNOWN BRAND');
		v_context_text := coalesce(v_row.context_text, p_context_text, '');
		v_reasoning := coalesce(v_row.reasoning, p_reasoning, 'Community consensus reached.');
		v_confidence := coalesce(v_row.ai_confidence, p_ai_confidence, 0.75);

		insert into public.products (
			barcode,
			name,
			brand,
			is_israeli,
			status,
			confidence,
			reasoning,
			context_text,
			verified_at,
			updated_at
		)
		values (
			p_barcode,
			v_name,
			v_brand,
			p_is_israeli,
			'verified',
			v_confidence,
			v_reasoning,
			v_context_text,
			now(),
			now()
		)
		on conflict (barcode)
		do update set
			name = excluded.name,
			brand = excluded.brand,
			is_israeli = excluded.is_israeli,
			status = excluded.status,
			confidence = excluded.confidence,
			reasoning = excluded.reasoning,
			context_text = excluded.context_text,
			verified_at = excluded.verified_at,
			updated_at = now();
	end if;

	return jsonb_build_object(
		'barcode', v_row.barcode,
		'is_israeli', v_row.is_israeli,
		'vote_count', v_row.vote_count,
		'verify_votes', v_row.verify_votes,
		'correct_votes', v_row.correct_votes,
		'verified', v_verified,
		'name', coalesce(v_row.name, p_name, 'UNKNOWN PRODUCT'),
		'brand', coalesce(v_row.brand, p_brand, 'UNKNOWN BRAND'),
		'context_text', coalesce(v_row.context_text, p_context_text, ''),
		'reasoning', coalesce(v_row.reasoning, p_reasoning, 'Community consensus recorded.'),
		'confidence', coalesce(v_row.ai_confidence, p_ai_confidence, 0.75)
	);
end;
$$;