// AUTO-GENERATED Supabase types (generated by MCP). Do not commit without review.
export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json | undefined }
	| Json[]

export type Database = {
	__InternalSupabase: { PostgrestVersion: "14.5" }
	public: {
		Tables: {
			audit_log: {
				Row: {
					created_at: string
					details: Json | null
					event_type: string
					id: string
					user_id: string | null
				}
				Insert: {
					created_at?: string
					details?: Json | null
					event_type: string
					id?: string
					user_id?: string | null
				}
				Update: {
					created_at?: string
					details?: Json | null
					event_type?: string
					id?: string
					user_id?: string | null
				}
				Relationships: []
			}
			opencorporates_cache: {
				Row: {
					cache_key: string
					cache_type: string
					created_at: string
					expires_at: string
					hit_count: number
					payload: Json
					status_code: number
					updated_at: string
				}
				Insert: {
					cache_key: string
					cache_type: string
					created_at?: string
					expires_at: string
					hit_count?: number
					payload: Json
					status_code?: number
					updated_at?: string
				}
				Update: {
					cache_key?: string
					cache_type?: string
					created_at?: string
					expires_at?: string
					hit_count?: number
					payload?: Json
					status_code?: number
					updated_at?: string
				}
				Relationships: []
			}
			pending_votes: {
				Row: {
					ai_confidence: number | null
					barcode: string
					brand: string | null
					context_text: string | null
					correct_votes: number
					created_at: string
					id: number
					is_israeli: boolean
					name: string | null
					reasoning: string | null
					updated_at: string
					verified: boolean
					verified_at: string | null
					verify_votes: number
					vote_count: number
				}
				Insert: {
					ai_confidence?: number | null
					barcode: string
					brand?: string | null
					context_text?: string | null
					correct_votes?: number
					created_at?: string
					id?: number
					is_israeli: boolean
					name?: string | null
					reasoning?: string | null
					updated_at?: string
					verified?: boolean
					verified_at?: string | null
					verify_votes?: number
					vote_count?: number
				}
				Update: {
					ai_confidence?: number | null
					barcode?: string
					brand?: string | null
					context_text?: string | null
					correct_votes?: number
					created_at?: string
					id?: number
					is_israeli?: boolean
					name?: string | null
					reasoning?: string | null
					updated_at?: string
					verified?: boolean
					verified_at?: string | null
					verify_votes?: number
					vote_count?: number
				}
				Relationships: []
			}
			products: {
				Row: {
					arbitration_log: string | null
					barcode: string
					brand: string
					category: string | null
					created_at: string
					id: number
					is_flagged: boolean
					origin_country: string
					parent_company: string
					parent_hq_country: string | null
					source_attribution: string | null
					updated_at: string
				}
				Insert: {
					arbitration_log?: string | null
					barcode: string
					brand?: string
					category?: string | null
					created_at?: string
					id?: number
					is_flagged?: boolean
					origin_country?: string
					parent_company?: string
					parent_hq_country?: string | null
					source_attribution?: string | null
					updated_at?: string
				}
				Update: {
					arbitration_log?: string | null
					barcode?: string
					brand?: string
					category?: string | null
					created_at?: string
					id?: number
					is_flagged?: boolean
					origin_country?: string
					parent_company?: string
					parent_hq_country?: string | null
					source_attribution?: string | null
					updated_at?: string
				}
				Relationships: []
			}
			quotas: {
				Row: {
					created_at: string
					id: string
					plan: string
					reset_date: string
					scans_limit: number
					scans_used: number
					updated_at: string
					user_id: string
				}
				Insert: {
					created_at?: string
					id?: string
					plan?: string
					reset_date?: string
					scans_limit?: number
					scans_used?: number
					updated_at?: string
					user_id: string
				}
				Update: {
					created_at?: string
					id?: string
					plan?: string
					reset_date?: string
					scans_limit?: number
					scans_used?: number
					updated_at?: string
					user_id?: string
				}
				Relationships: [
					{
						foreignKeyName: "quotas_user_id_fkey"
						columns: ["user_id"]
						isOneToOne: false
						referencedRelation: "users"
						referencedColumns: ["id"]
					},
				]
			}
			scan_history: {
				Row: {
					barcode: string
					brand: string | null
					category: string | null
					confidence_score: number | null
					created_at: string | null
					id: string
					is_flagged: boolean | null
					origin_country: string | null
					parent_company: string | null
					parent_hq_country: string | null
					product_name: string | null
					scanned_at: string | null
					user_id: string | null
				}
				Insert: {
					barcode: string
					brand?: string | null
					category?: string | null
					confidence_score?: number | null
					created_at?: string | null
					id?: string
					is_flagged?: boolean | null
					origin_country?: string | null
					parent_company?: string | null
					parent_hq_country?: string | null
					product_name?: string | null
					scanned_at?: string | null
					user_id?: string | null
				}
				Update: {
					barcode?: string
					brand?: string | null
					category?: string | null
					confidence_score?: number | null
					created_at?: string | null
					id?: string
					is_flagged?: boolean | null
					origin_country?: string | null
					parent_company?: string | null
					parent_hq_country?: string | null
					product_name?: string | null
					scanned_at?: string | null
					user_id?: string | null
				}
				Relationships: []
			}
			subscriptions: {
				Row: {
					created_at: string | null
					id: string
					period_end: string
					period_start: string
					plan: string
					scan_limit: number
					scans_used: number
					stripe_customer_id: string | null
					stripe_subscription_id: string | null
					user_id: string | null
				}
				Insert: {
					created_at?: string | null
					id?: string
					period_end?: string
					period_start?: string
					plan?: string
					scan_limit?: number
					scans_used?: number
					stripe_customer_id?: string | null
					stripe_subscription_id?: string | null
					user_id?: string | null
				}
				Update: {
					created_at?: string | null
					id?: string
					period_end?: string
					period_start?: string
					plan?: string
					scan_limit?: number
					scans_used?: number
					stripe_customer_id?: string | null
					stripe_subscription_id?: string | null
					user_id?: string | null
				}
				Relationships: []
			}
			users: {
				Row: {
					created_at: string
					email: string
					id: string
					plan: string
					updated_at: string
				}
				Insert: {
					created_at?: string
					email: string
					id?: string
					plan?: string
					updated_at?: string
				}
				Update: {
					created_at?: string
					email?: string
					id?: string
					plan?: string
					updated_at?: string
				}
				Relationships: []
			}
		}
		Views: {
			[_ in never]: never
		}
		Functions: {
			bytea_to_text: { Args: { data: string }; Returns: string }
			check_user_quota: {
				Args: { p_user_id: string }
				Returns: {
					allowed: boolean
					plan: string
					scans_remaining: number
				}[]
			}
			http: {
				Args: { request: Database["public"]["CompositeTypes"]["http_request"] }
				Returns: Database["public"]["CompositeTypes"]["http_response"]
				SetofOptions: {
					from: "http_request"
					to: "http_response"
					isOneToOne: true
					isSetofReturn: false
				}
			}
			http_delete:
				| {
						Args: { uri: string }
						Returns: Database["public"]["CompositeTypes"]["http_response"]
						SetofOptions: {
							from: "*"
							to: "http_response"
							isOneToOne: true
							isSetofReturn: false
						}
					}
				| {
						Args: { content: string; content_type: string; uri: string }
						Returns: Database["public"]["CompositeTypes"]["http_response"]
						SetofOptions: {
							from: "*"
							to: "http_response"
							isOneToOne: true
							isSetofReturn: false
						}
					}
			http_get:
				| {
						Args: { uri: string }
						Returns: Database["public"]["CompositeTypes"]["http_response"]
						SetofOptions: {
							from: "*"
							to: "http_response"
							isOneToOne: true
							isSetofReturn: false
						}
					}
				| {
						Args: { data: Json; uri: string }
						Returns: Database["public"]["CompositeTypes"]["http_response"]
						SetofOptions: {
							from: "*"
							to: "http_response"
							isOneToOne: true
							isSetofReturn: false
						}
					}
			http_head: {
				Args: { uri: string }
				Returns: Database["public"]["CompositeTypes"]["http_response"]
				SetofOptions: {
					from: "*"
					to: "http_response"
					isOneToOne: true
					isSetofReturn: false
				}
			}
			http_header: {
				Args: { field: string; value: string }
				Returns: Database["public"]["CompositeTypes"]["http_header"]
				SetofOptions: {
					from: "*"
					to: "http_header"
					isOneToOne: true
					isSetofReturn: false
				}
			}
			http_list_curlopt: {
				Args: never
				Returns: {
					curlopt: string
					value: string
				}[]
			}
			http_patch: {
				Args: { content: string; content_type: string; uri: string }
				Returns: Database["public"]["CompositeTypes"]["http_response"]
				SetofOptions: {
					from: "*"
					to: "http_response"
					isOneToOne: true
					isSetofReturn: false
				}
			}
			http_post:
				| {
						Args: { content: string; content_type: string; uri: string }
						Returns: Database["public"]["CompositeTypes"]["http_response"]
						SetofOptions: {
							from: "*"
							to: "http_response"
							isOneToOne: true
							isSetofReturn: false
						}
					}
				| {
						Args: { data: Json; uri: string }
						Returns: Database["public"]["CompositeTypes"]["http_response"]
						SetofOptions: {
							from: "*"
							to: "http_response"
							isOneToOne: true
							isSetofReturn: false
						}
					}
			http_put: {
				Args: { content: string; content_type: string; uri: string }
				Returns: Database["public"]["CompositeTypes"]["http_response"]
				SetofOptions: {
					from: "*"
					to: "http_response"
					isOneToOne: true
					isSetofReturn: false
				}
			}
			http_reset_curlopt: { Args: never; Returns: boolean }
			http_set_curlopt: {
				Args: { curlopt: string; value: string }
				Returns: boolean
			}
			increment_and_verify: {
				Args: {
					p_ai_confidence?: number
					p_barcode: string
					p_brand?: string
					p_context_text?: string
					p_is_israeli: boolean
					p_name?: string
					p_reasoning?: string
					p_vote_action?: string
				}
				Returns: Json
			}
			increment_quota_usage: {
				Args: { p_user_id: string }
				Returns: {
					allowed: boolean
					scans_remaining: number
				}[]
			}
			prune_opencorporates_cache: { Args: never; Returns: number }
			reset_daily_quotas: { Args: never; Returns: undefined }
			text_to_bytea: { Args: { data: string }; Returns: string }
			urlencode:
				| { Args: { data: Json }; Returns: string }
				| {
						Args: { string: string }
						Returns: {
							error: true
						} & "Could not choose the best candidate function between: public.urlencode(string => bytea), public.urlencode(string => varchar). Try renaming the parameters or the function itself in the database so function overloading can be resolved"
					}
				| {
						Args: { string: string }
						Returns: {
							error: true
						} & "Could not choose the best candidate function between: public.urlencode(string => bytea), public.urlencode(string => varchar). Try renaming the parameters or the function itself in the database so function overloading can be resolved"
					}
		}
		Enums: {
			[_ in never]: never
		}
		CompositeTypes: {
			http_header: {
				field: string | null
				value: string | null
			}
			http_request: {
				method: unknown
				uri: string | null
				headers: Database["public"]["CompositeTypes"]["http_header"][] | null
				content_type: string | null
				content: string | null
			}
			http_response: {
				status: number | null
				content_type: string | null
				headers: Database["public"]["CompositeTypes"]["http_header"][] | null
				content: string | null
			}
		}
	}
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
	DefaultSchemaTableNameOrOptions extends
		| keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals
	}
		? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
				DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals
}
	? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
			DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
			Row: infer R
		}
		? R
		: never
	: DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
				DefaultSchema["Views"])
		? (DefaultSchema["Tables"] &
				DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
				Row: infer R
			}
			? R
			: never
		: never

export type TablesInsert<
	DefaultSchemaTableNameOrOptions extends
		| keyof DefaultSchema["Tables"]
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
			Insert: infer I
		}
		? I
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
		? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
				Insert: infer I
			}
			? I
			: never
		: never

export type TablesUpdate<
	DefaultSchemaTableNameOrOptions extends
		| keyof DefaultSchema["Tables"]
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
			Update: infer U
		}
		? U
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
		? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
				Update: infer U
			}
			? U
			: never
		: never

export type Enums<
	DefaultSchemaEnumNameOrOptions extends
		| keyof DefaultSchema["Enums"]
		| { schema: keyof DatabaseWithoutInternals },
	EnumName extends DefaultSchemaEnumNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
		: never = never,
> = DefaultSchemaEnumNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals
}
	? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
	: DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
		? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
		: never

export type CompositeTypes<
	PublicCompositeTypeNameOrOptions extends
		| keyof DefaultSchema["CompositeTypes"]
		| { schema: keyof DatabaseWithoutInternals },
	CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals
	}
		? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
		: never = never,
> = PublicCompositeTypeNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals
}
	? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
	: PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
		? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
		: never

export const Constants = {
	public: {
		Enums: {},
	},
} as const
